# conda env create --file environment.yml
# mamba env create --file environment.yml
name: ufc_events_eda
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - lightgbm
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pip
  - plotly
  - pyjanitor
  - pylint
  - pyprojroot
  - python=3.10
  - python-dotenv
  - seaborn
  - statsmodels
