name: Get data and upload viz workflow

on:
  schedule:
    - cron: "0 13 * * 0"

jobs:
  get_data:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      API_KEY: ${{secrets.API_KEY}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ufc_events_eda
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false
          auto-update-conda: true
      - run: |
          pip install --editable .
          python ufc_events_eda/data/make_dataset.py
          jupyter nbconvert --to notebook --execute notebooks/1-cvillafraz-data-processing.ipynb
          jupyter nbconvert --to notebook --execute notebooks/2-cvillafraz-events-analysis.ipynb
          jupyter nbconvert --to notebook --execute notebooks/3-cvillafraz-fights-analysis.ipynb
          python ufc_events_eda/visualization/upload_viz.py
      - name: Commit data file
        id: commit
        run: |
          git config --local user.email "cirov@protonmail.com"
          git config --local user.name "cvillafraz"
          git add data/raw/ufc_events.json
          git commit -m "Get raw dataset on $(date '+%b %d %Y')" -a
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
