name: Get UFC Events Workflow

on: push

jobs:
  get_data:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{secrets.API_KEY}}

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6 # Install the python version needed

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "gh_requirements.txt"

      - name: Execute job script # Run scripts/run_job.py
        run: |
          pip install --editable .
          python ufc_events_eda/data/make_dataset.py

      - name: Commit data file
        id: commit
        run: |
          git config --local user.email "cirov@protonmail.com"
          git config --local user.name "cvillafraz"
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Get raw dataset on $(date '+%b %d %Y')" -a
            echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
